#!/usr/bin/env python3
"""Parse exported exam HTML into weekly exam JSON / JS."""

import html as htmlmod
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
DATA_DIR = ROOT / "data"

SOURCES = [
    {
        "id": "weekly-camp8",
        "title": "第八季普心训练营结营测评",
        "subtitle": "50 题 · 每题 2 分",
        "source": "400_第八季普心训练营结营测评",
        "path": Path("/Users/zhongyaoyao/Downloads/400_第八季普心训练营结营测评-11019d13bebb.html"),
    },
    {
        "id": "weekly-312-2026",
        "title": "2026心理学统考312二战测评",
        "subtitle": "100 题 · 每题 3 分",
        "source": "401_2026心理学统考312二战测评",
        "path": Path("/Users/zhongyaoyao/Downloads/401_2026心理学统考312二战测评.html"),
    },
]


def strip_tags(s: str, preserve_breaks: bool = False) -> str:
    s = re.sub(r"<br\s*/?>", "\n", s, flags=re.I)
    s = re.sub(r"</p>\s*<p>", "\n", s, flags=re.I)
    s = re.sub(r"<[^>]+>", "", s)
    s = htmlmod.unescape(s).replace("\xa0", " ")
    if preserve_breaks:
        lines = [re.sub(r"[ \t]+", " ", line).strip() for line in s.splitlines()]
        return "\n".join(line for line in lines if line)
    return re.sub(r"\s+", " ", s).strip()


def parse_exam(path: Path) -> list:
    text = path.read_text(encoding="utf-8", errors="replace")
    blocks = re.split(r"<h1[^>]*>第\s*(\d+)\s*题</h1>", text)[1:]
    questions = []
    for i in range(0, len(blocks), 2):
        num = int(blocks[i])
        chunk = blocks[i + 1]
        stem_m = re.search(r"color:\s*blue[^>]*>\s*(<p>.*?</p>)", chunk, re.S)
        stem = strip_tags(stem_m.group(1)) if stem_m else ""
        score_m = re.search(r"\((\d+)分\)", chunk)
        score = int(score_m.group(1)) if score_m else None
        opts = []
        for om in re.finditer(
            r"<span[^>]*>([A-D])、</span>\s*<span[^>]*>(.*?)</span>\s*"
            r"<span[^>]*>\s*&nbsp;&nbsp;\(ID:\s*(op_[^)]+)\)",
            chunk,
            re.S,
        ):
            opts.append(
                {"key": om.group(1), "text": strip_tags(om.group(2)), "id": om.group(3).strip()}
            )
        expl_parts = re.split(r"<h3>\s*题目解析\s*</h3>", chunk, maxsplit=1)
        explanation = ""
        correct_id = None
        if len(expl_parts) > 1:
            after = expl_parts[1]
            ans_m = re.search(
                r"正确答案:\s*</span>\s*<span[^>]*>\s*&nbsp;&nbsp;(op_[^\s（]+)", after
            )
            if ans_m:
                correct_id = ans_m.group(1).strip()
            expl_text = re.split(r"<span[^>]*>\s*正确答案:", after)[0]
            explanation = strip_tags(expl_text, preserve_breaks=True)
        correct_key = next((o["key"] for o in opts if o["id"] == correct_id), None)
        if not explanation and correct_key:
            opt_text = next((o["text"] for o in opts if o["key"] == correct_key), "")
            explanation = f"正确答案：{correct_key}. {opt_text}" if opt_text else f"正确答案：{correct_key}"
        questions.append(
            {
                "number": num,
                "stem": stem,
                "score": score,
                "options": opts,
                "correctKey": correct_key,
                "explanation": explanation or "暂无解析",
            }
        )
    return questions


def main():
    exams = []
    for src in SOURCES:
        if not src["path"].exists():
            raise SystemExit(f"Missing source file: {src['path']}")
        qs = parse_exam(src["path"])
        exams.append(
            {
                "id": src["id"],
                "title": src["title"],
                "subtitle": src["subtitle"],
                "source": src["source"],
                "type": "weekly",
                "questionCount": len(qs),
                "questions": qs,
            }
        )
        print(f"{src['id']}: {len(qs)} questions")

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    json_path = DATA_DIR / "weekly.json"
    json_path.write_text(json.dumps(exams, ensure_ascii=False, indent=2), encoding="utf-8")

    js_path = DATA_DIR / "weekly.js"
    js_path.write_text(
        "/* Auto-generated by parse_exams.py */\n"
        "window.WEEKLY_EXAMS = "
        + json.dumps(exams, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {json_path} and {js_path}")


if __name__ == "__main__":
    main()
